packages:
  - "packages/*"
  - "apps/*"

catalogs:
  web:
    "@arco-design/web-react": "^2.66.1"
    clsx: ^2.1.1
    react: "^18.3.1"
    react-dom: "^18.3.1"
    "@tanstack/react-table": "^8.21.3"
    next: "15.3.2"
    typescript: "^5"
    "@types/node": "^22"
    "@types/react": "^18"
    "@types/react-dom": "^18"
    "@tailwindcss/postcss": "^4"
    tailwindcss: "^4"
    eslint: "^9"
    "eslint-config-next": "15.3.2"
    "@eslint/eslintrc": "^3"
    pg: ^8.16.0
    "zod": "^3.24.4"
    "zod-validation-error": "^3.4.1"
    "tw-animate-css": "^1.3.0"
    "date-fns": "^4.1.0"
    "tailwind-merge": "^3.3.0"
  server:
    bcryptjs: ^3
    fastify: ^5.3.3
    "fastify-plugin": ^5.0.1
    "@fastify/cors": ^11.0.1
    "@fastify/postgres": ^6.0.2
    "@faker-js/faker": "^9.8.0"
    nodemon: ^3.1.10
    "p-retry": ^6.2.1
    pg: ^8.16.0
    jose: ^6
    typescript: ^5.7.2
    ts-node: ^10.9.2
    "@types/node": ^22
    "@fastify/type-provider-typebox": ^5.1.0
    "@sinclair/typebox": ^0.34.33
